config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  devise_for :users, controllers: {
    registrations: "users/registrations",
  }
  root to: 'articles#index'
  get 'tasks/:id' , to: 'articles#notice'
  resources :users, only: [:show] do
    resources :pets, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :tasks
  end
  resources :articles, only: [:new, :create, :show, :edit, :update, :destroy]
end

app/models/task.rb
class Task < ApplicationRecord

  with_options presence: true do
    validates :title
    validates :start_time
  end

  with_options presence: true, numericality: { message: 'を選択してください' } do
    validates :task_type_id
    validates :notice_id
  end


  belongs_to :user


  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :task_type
  belongs_to :notice
end

app/models/task_type.rb
class TaskType < ActiveHash::Base
  self.data = [
    { id: 1, name: '予定' },
    { id: 2, name: '記録' }
  ]

  include ActiveHash::Associations
  has_many :tasks
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :move_to_root_path_only_index, only: [:index]
  before_action :task_find, only: [:show, :edit, :update, :destroy]
  before_action :move_to_root_path, only: [:edit, :update, :destroy]


  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to user_tasks_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to user_tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to user_tasks_path(@task.user_id)
  end


  private

  def task_params
    params.require(:task).permit(:start_time, :title, :content, :task_type_id, :notice_id).merge(user_id: current_user.id)
  end

  def task_find
    @task = Task.find(params[:id])
  end

  def move_to_root_path_only_index
    redirect_to root_path unless current_user.id == params[:user_id].to_i
  end

  def move_to_root_path
    redirect_to root_path unless current_user == @task.user
  end


end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/edit.html.erb
<%= render "shared/second-header"%>


<%= form_with model: @task, url: user_task_path, class: 'registration-main', local: true do |f| %>
  <div class='article-form-wrap'>
    <div class='article-form-header'>
      <h1 class='article-form-header-text'>
        New Task
      </h1>
    </div>

    
  <%= render "shared/error_messages", model: f.object %>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Date
        </label>
      </div>
      <%= f.datetime_field :start_time, class:"article-title", id:"article-title", type: "datetime-local" %>
    </div>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Title
        </label>
      </div>
      <%= f.text_field :title, class:"article-title", id:"article-title", placeholder:"タイトル欄", maxlength:"50" %>
    </div>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        Text
        </label>
      </div>
      <%= f.text_area :content, class:"article-text", id:"article-text", placeholder:"詳細等"%>
    </div>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Task Type
        </label>
      </div>
      <div class='publishing-setting-form'>
        <%= f.collection_radio_buttons(:task_type_id, TaskType.all, :id, :name, {}, {class:"task-type-select"}) %>
      </div>
    </div>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Notice
        </label>
      </div>
      <div class='publishing-setting-form'>
        <%= f.collection_radio_buttons(:notice_id, Notice.all, :id, :name, {}, {class:"notice-select"}) %>
      </div>
                  <p class='info-text'>※現在より先の日程の記録は自動的に非通知になります</p>

    </div>


    <div class='register-btn'>
      <p class='enter-btn'>
        <%= image_submit_tag("enter_btn3.png", class:"btn") %>
      </p>
    </div>
  </div>
<% end %>

<%= render "shared/footer" %>

app/views/tasks/index.html.erb
<body class='calendar-top'>
<%= render "shared/second-header"%>
<div class='calendar-info'>
  <div class='plus-task-btn'>
  <%= link_to '予定・記録の追加', new_user_task_path(), class: 'plus-task' %>
  </div>
  <ul class='task-info'>
    <li class='yotei-look'>
      予定
    </li>
    <li class='kiroku-look'>
      記録
    </li>
  </ul>
</div>
<%= month_calendar events: @tasks do |date, tasks| %>
  <%= date.day %>

    <% tasks.each do |task| %>
    <% if task.user_id == current_user.id %>
      <% if task.task_type_id == 1 %>
        <div class='yotei'>
          <%= link_to task.title, user_task_path(id: task.id), class: 'yotei-link' %>
        </div>
      <% else %>
        <div class='kiroku'>
          <%= link_to task.title, user_task_path(id: task.id), class: 'kiroku-link' %>
        </div>
      <% end %>
      <% end %>
  <% end %>
<% end %>
</body>

<%= render "shared/footer" %>

app/views/tasks/new.html.erb
<%= render "shared/second-header"%>


<%= form_with model: @task, url: user_tasks_path, method: :create, class: 'registration-main', local: true do |f| %>
  <div class='article-form-wrap'>
    <div class='article-form-header'>
      <h1 class='article-form-header-text'>
        New Task
      </h1>
    </div>

    
  <%= render "shared/error_messages", model: f.object %>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Date
        </label>
      </div>
      <%= f.datetime_field :start_time, class:"article-title", id:"article-title", type: "datetime-local" %>
    </div>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Title
        </label>
      </div>
      <%= f.text_field :title, class:"article-title", id:"article-title", placeholder:"タイトル欄", maxlength:"50" %>
    </div>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        Text
        </label>
      </div>
      <%= f.text_area :content, class:"article-text", id:"article-text", placeholder:"詳細等"%>
    </div>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Task Type
        </label>
      </div>
      <div class='publishing-setting-form'>
        <%= f.collection_radio_buttons(:task_type_id, TaskType.all, :id, :name, {}, {class:"task-type-select"}) %>
      </div>
    </div>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Notice
        </label>
      </div>
      <div class='publishing-setting-form'>
        <%= f.collection_radio_buttons(:notice_id, Notice.all, :id, :name, {}, {class:"notice-select"}) %>
      </div>
            <p class='info-text'>※現在より先の日程の記録は自動的に非通知になります</p>
    </div>


    <div class='register-btn'>
      <p class='enter-btn'>
        <%= image_submit_tag("enter_btn3.png", class:"btn") %>
      </p>
    </div>
  </div>
<% end %>

<%= render "shared/footer" %>

app/views/tasks/show.html.erb
<%= render "shared/second-header"%>


<div class='registration-main'>
  <div class='mypage-wrap'>
    <div class='mypage-header'>
      <h1 class='mypage-header-text'>
        Task
      </h1>
    </div>

    

    <div class="mypage-group">
      <div class='mypage-text-wrap'>
        <label class="mypage-text">
        Date
        </label>
      </div>
      <p class='nickname-mypage'><%= @task.start_time %></p>
    </div>



    <div class="mypage-group">
      <div class='mypage-text-wrap'>
        <label class="mypage-text">
        Title
        </label>
      </div>
      <p class='gender-mypage'><%= @task.title %></p>
    </div>

    <div class="mypage-group">
      <div class='mypage-text-wrap'>
        <label class="mypage-text">
        Content
        </label>
      </div>
      <p class='profile-mypage'><%= @task.content %></p>
    </div>

    <div class="mypage-group">
      <div class='mypage-text-wrap'>
        <label class="mypage-text">
        Task type
        </label>
      </div>
        <p class='nickname-mypage', id='pet-birthday'><%= @task.task_type.name %></p>
      </div>

    <div class="mypage-group">
      <div class='mypage-text-wrap'>
        <label class="mypage-text">
        Notice
        </label>
      </div>
        <p class='nickname-mypage'><%= @task.notice.name %></p>
      </div>

    <% if current_user == @task.user %>
      <div class='go-edit-btn'>
        <%= link_to 'Edit Task', edit_user_task_path(@task.user_id), class: "go-edit" %>
      </div>

      <div class='go-delete-btn'>
        <%= link_to 'Delete Task ?', user_task_path(@task.user_id), method: :delete, data: { confirm: "【確認】このTaskを削除してもよろしいですか？" }, class: "go-delete" %>
      </div>
    <% end %>

  </div>
</div>

<%= render "shared/footer" %>