config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  devise_for :users, controllers: {
    registrations: "users/registrations",
  }
  root to: 'articles#index'
  get 'tasks/:id' , to: 'articles#notice'
  resources :users, only: [:show] do
    resources :pets, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :tasks
  end
  resources :articles, only: [:new, :create, :show, :edit, :update, :destroy]
end

app/models/article.rb
class Article < ApplicationRecord

  with_options presence: true do
    validates :title
    validates :image
    validates :text, length: { maximum: 400, message: 'は400文字以内で記入してください' }
    validates :pet_type_id, numericality: { other_than: 1, message: 'を選択してください' }
    validates :text_type_id, numericality: { other_than: 1, message: 'を選択してください' }
    validates :publishing_setting_id, numericality: { message: 'を選択してください' }
    validates :user
  end


  belongs_to :user
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :pet_type
  belongs_to :text_type
  belongs_to :publishing_setting
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :article_find, only: [:show, :edit, :update, :destroy]
  before_action :move_to_root_path, only: [:edit, :update, :destroy]


  def index
    if user_signed_in?
     @user = current_user.id
    end
    @articles = Article.all
    @tasks = Task.all.order('task_type_id ASC')
    end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show

  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to article_path
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end

  def notice
    task = Task.find(params[:id])
    task.increment!(:notice_id, 1)

    notice = Task.find(params[:id])
    render json:{ task: notice }

  end

  private

  def article_params
    params.require(:article).permit(:image, :title, :text, :pet_type_id, :text_type_id, :publishing_setting_id).merge(user_id: current_user.id)
  end

  def article_find
    @article = Article.find(params[:id])
  end

  def move_to_root_path
    redirect_to root_path unless current_user == @article.user
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%= render "shared/second-header"%>


<%= form_with model: @article, class: 'registration-main', local: true do |f| %>
  <div class='article-form-wrap'>
    <div class='article-form-header'>
      <h1 class='article-form-header-text'>
        New Article
      </h1>
    </div>

    
  <%= render "shared/error_messages", model: f.object %>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Title
        </label>
      </div>
      <%= f.text_field :title, class:"article-title", id:"article-title", placeholder:"タイトル欄", maxlength:"50" %>
    </div>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Image
        </label>
      </div>
      <%= f.file_field :image, class:"article-title", id:"article-image" %>
    </div>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Text
        </label>
      </div>
      <%= f.text_area :text, class:"article-text", id:"article-text", placeholder:"本文"%>
    </div>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Pet Type
        </label>
      </div>
      <div class='pet-type-form'>
        <%= f.collection_select(:pet_type_id, PetType.all, :id, :name, {}, {class:"pet-type-select"}) %>
      </div>
    </div>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Text Type
        </label>
      </div>
      <div class='text-type-form'>
        <%= f.collection_select(:text_type_id, TextType.all, :id, :name, {}, {class:"text-type-select"}) %>
      </div>
    </div>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Publishing_setting
        </label>
      </div>
      <div class='publishing-setting-form'>
        <%= f.collection_radio_buttons(:publishing_setting_id, PublishingSetting.all, :id, :name, {}, {class:"publishing-setting-select"}) %>
      </div>
    </div>

    <div class='register-btn'>
      <p class='enter-btn'>
        <%= image_submit_tag("enter_btn3.png", class:"btn") %>
      </p>
    </div>
  </div>
<% end %>

<%= render "shared/footer" %>

app/views/articles/index.html.erb
<%= render "shared/header" %>
<div class='main'>
  <% if user_signed_in? %>
    <div class='side-bar-area'>
      <%= render "shared/side_bar" %>
    </div>
  <% end %>
  <%# 画面上部通知部分 %>
  <div class='main-area'>
    <% if user_signed_in? %>
      <div class='notices-contents'>
        <div class='date'>
          <p class='top-today'>
            <%= require 'date'
                date = DateTime.now # 現在のDateTimeオブジェクトを取得
                p date.strftime("%Y年%m月%d日") %>
          </p>
        </div>
        <div class='notices-box'>
          <div class='all-notices'>
            <% @tasks.each do |task| %>
              <% if task.user_id == current_user.id %>
                <% if task.notice_id == 1 %>
                  <div class='top-notice'>
                    <% if task.task_type_id == 1 %>
                      <% if (task.start_time.to_date - Date.current).to_i > 0 %>                      
                        <p class='top-yotei', id=<%= task.id %>>
                          <%= "【" + task.title + "】" + 'の予定まで' + "#{ (task.start_time.to_date - Date.current).to_i}" + '日です' %>
                          <div class='notice-end', id=<%= "yotei-notice-off-#{task.id}" %>>
                            通知終了
                          </div>
                        </p>
                      <% else %>
                        <p class='yotei-change-kiroku', id=<%= task.id %>>
                          <% task.update( task_type_id: 2) %>
                          <%= "【" + task.title + "】" + 'の記録から' + "#{ (task.start_time.to_date - Date.current).to_i.abs}" + '日経過です' %>
                          <div class='notice-end', id=<%= "yotei-notice-off-#{task.id}" %>>
                            通知終了
                          </div>
                        </p>
                      <% end %>
                    <% else %>
                      <p class='top-kiroku', id=<%= task.id %>>
                        <% if (task.start_time.to_date - Date.current).to_i < 0 %>
                        <%= "【" + task.title + "】" + 'の記録から' + "#{ (task.start_time.to_date - Date.current).to_i.abs}" + '日経過です' %>
                        <div class='notice-end', id=<%= "kiroku-notice-off-#{task.id}" %>>
                          通知終了
                        </div>
                        <% else %>
                        <% task.update( notice_id: 2) %>
                        <% end %>
                      </p>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

    <%# 画面上部通知部分 %>

    <%# 投稿記事表示部分 %>
    <div class='main-contents'>
      <div class='main-page'>
        <div class='all-articles'>
          all articles

          <ul class='article-lists'>

            <% @articles.order('created_at DESC').each do |article| %>
              <% if article.publishing_setting_id == 1 %>
                <li class='list'>
                  <%= link_to article_path(article.id), class: "article-content" do %>
                    <div class='article-img-content'>
                      <%= image_tag article.image, class: "article-img" %>
                    </div>
                    <div class='article-info'>
                      <h3 class='article-name'>
                        <%= article.title %>
                      </h3>
                      <div class='user-nickname'>
                        <span><%= article.user.nickname %></span>
                      </div>
                    </div>
                  <% end %>
                </li>
              <% end %>
            <% end %>
          </ul>

        </div>
        <div class='mostlike-articles'>
          most like articles
        </div>
        <div class='favorite-articles'>
          my favorite articles
        </div>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

app/views/articles/new.html.erb
<%= render "shared/second-header"%>


<%= form_with model: @article, url: articles_path, method: :create, class: 'registration-main', local: true do |f| %>
  <div class='article-form-wrap'>
    <div class='article-form-header'>
      <h1 class='article-form-header-text'>
        New Article
      </h1>
    </div>

    
  <%= render "shared/error_messages", model: f.object %>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Title
        </label>
      </div>
      <%= f.text_field :title, class:"article-title", id:"article-title", placeholder:"タイトル欄", maxlength:"50" %>
    </div>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Image
        </label>
      </div>
      <%= f.file_field :image, class:"article-image", id:"article-image" %>
    </div>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Text
        </label>
      </div>
      <%= f.text_area :text, class:"article-text", id:"article-text", placeholder:"本文"%>
    </div>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Pet Type
        </label>
      </div>
      <div class='pet-type-form'>
        <%= f.collection_select(:pet_type_id, PetType.all, :id, :name, {}, {class:"pet-type-select"}) %>
      </div>
    </div>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Text Type
        </label>
      </div>
      <div class='text-type-form'>
        <%= f.collection_select(:text_type_id, TextType.all, :id, :name, {}, {class:"text-type-select"}) %>
      </div>
    </div>

    <div class="article-form-group">
      <div class='article-form-text-wrap'>
        <label class="article-form-text">
        <span class='not-nil'>*</span> Publishing_setting
        </label>
      </div>
      <div class='publishing-setting-form'>
        <%= f.collection_radio_buttons(:publishing_setting_id, PublishingSetting.all, :id, :name, {}, {class:"publishing-setting-select"}) %>
      </div>
    </div>

    <div class='register-btn'>
      <p class='enter-btn'>
        <%= image_submit_tag("enter_btn3.png", class:"btn") %>
      </p>
    </div>
  </div>
<% end %>

<%= render "shared/footer" %>

app/views/articles/show.html.erb
<%= render "shared/second-header"%>


<div class='registration-main'>
  <div class='article-show-wrap'>
    <div class='article-show-header'>
      <h1 class='article-show-header-text'>
        <%= @article.title %>
      </h1>
    </div>

    <div class="article-show-group">
      <%= image_tag @article.image ,class:"article-show-image" %>
    </div>

    <div class="article-show-group">
      <p class='article-show-text'><%= @article.text %></p>
    </div>

    <div class="article-show-group">
      <div class='article-show-text-wrap'>
        <label class="article-show-info">
        PetType
        </label>
      </div>
      <p class='article-show-pet-type'><%= @article.pet_type.name %></p>
    </div>



    <div class="article-show-group">
      <div class='mypage-text-wrap'>
        <label class="article-show-info">
        TextType
        </label>
      </div>
      <p class='article-show-text-type'><%= @article.text_type.name %></p>
    </div>

    <% if current_user.id == @article.user_id %>
      <div class='go-btn'>
        <div class='go-edit-btn'>
          <%= link_to 'Edit Article', edit_article_path(@article.id), class: "go-edit" %>
        </div>
        <div class='go-delete-btn'>
          <%= link_to 'Delete Article', article_path(@article.id), method: :delete, data: { confirm: "【確認】このArticleを削除してもよろしいですか？" }, class: "go-delete" %>
        </div>
      </div>
    <% end %>

  </div>
</div>

<%= render "shared/footer" %>