config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  devise_for :users, controllers: {
    registrations: "users/registrations",
  }
  root to: 'articles#index'
  get 'tasks/:id' , to: 'articles#notice'
  resources :users, only: [:show] do
    resources :pets, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :tasks
  end
  resources :articles, only: [:new, :create, :show, :edit, :update, :destroy]
end

app/models/pet.rb
class Pet < ApplicationRecord

  with_options presence: true do
    validates :name
    validates :image
    validates :pet_type_id, numericality: { other_than: 1, message: 'を選択してください' }
    validates :feature
    validates :user
  end

  belongs_to :user
  has_one_attached :image

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :pet_type

end

app/models/pet_type.rb
class PetType < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '犬' },
    { id: 3, name: '猫' },
    { id: 4, name: 'フェレット' },
    { id: 5, name: 'モルモット' },
    { id: 6, name: 'ハムスター' },
    { id: 7, name: 'ハリネズミ' },
    { id: 8, name: 'チンチラ' },
    { id: 9, name: 'デグー' },
    { id: 10, name: 'インコ' },
    { id: 11, name: '小鳥' },
    { id: 12, name: 'あひる' },
    { id: 13, name: 'ふくろう' },
    { id: 14, name: 'リス' },
    { id: 15, name: 'うさぎ' },
    { id: 16, name: '魚' },
    { id: 17, name: 'レオパ' },
    { id: 18, name: 'トカゲ' },
    { id: 19, name: 'ヘビ' },
    { id: 20, name: 'その他' }
  ]

  include ActiveHash::Associations
  has_many :articles
  has_many :pets
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :pet_find, only: [:show, :edit, :update, :destroy]
  before_action :move_to_root_path_only_new, only: [:new, :create]
  before_action :move_to_root_path, only: [:edit, :update, :destroy]


  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)

    if @pet.save
      redirect_to user_path(@pet.user_id)
    else
      render :new
    end
  end

  def show

  end

  def edit
  end

  def update
    if @pet.update(pet_params)
      redirect_to user_pet_path
    else
      render :edit
    end
  end

  def destroy
    @pet.destroy
    redirect_to user_path(@pet.user_id)
  end


  private

  def pet_params
    params.require(:pet).permit(:name, :image, :pet_type_id, :feature, :birthday, :age).merge(user_id: current_user.id)
  end

  def pet_find
    @pet = Pet.find(params[:user_id])
  end

  def move_to_root_path_only_new
    redirect_to root_path unless current_user.id == params[:user_id].to_i
  end

  def move_to_root_path
    redirect_to root_path unless current_user == @pet.user
  end

end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/pets/edit.html.erb
<%= render "shared/second-header"%>


<%= form_with model: @pet, url: user_pet_path, class: 'registration-main', local: true do |f| %>
  <div class='pet-form-wrap'>
    <div class='pet-form-header'>
      <h1 class='pet-form-header-text'>
        YourPet
      </h1>
    </div>

    
  <%= render "shared/error_messages", model: f.object %>

    <div class="pet-form-group">
      <div class='pet-form-text-wrap'>
        <label class="pet-form-text">
        <span class='not-nil'>*</span> Name
        </label>
      </div>
      <%= f.text_field :name, class:"pet-name-form", id:"name", placeholder:"ペットの名前", maxlength:"20" %>
    </div>

    <div class="pet-form-group">
      <div class='pet-form-text-wrap'>
        <label class="pet-form-text">
        <span class='not-nil'>*</span> Image
        </label>
      </div>
      <%= f.file_field :image, class:"pet-image-form", id:"pet-image" %>
    </div>

    <div class="pet-form-group">
      <div class='pet-form-text-wrap'>
        <label class="pet-form-text">
        <span class='not-nil'>*</span> Pet Type
        </label>
      </div>
      <div class='pet-type-form'>
        <%= f.collection_select(:pet_type_id, PetType.all, :id, :name, {}, {class:"pet-type-select"}) %>
      </div>
    </div>

    <div class="pet-form-group">
      <div class='pet-form-text-wrap'>
        <label class="pet-form-text">
        <span class='not-nil'>*</span> Feature
        </label>
      </div>
      <%= f.text_area :feature, class:"pet-feature-form", id:"feature", placeholder:"種類や色など、特徴を記入" %>
    </div>

    <div class="pet-form-group">
      <div class='pet-form-text-wrap'>
        <label class="pet-form-text">
         Birthday
        </label>
      </div>
      <div class='input-pet-birth-wrap'>
        <%= raw sprintf(
                    f.date_select(
                      :birthday,
                      class:'select-pet-birth',
                      id:"pet-birth-date",
                      use_month_numbers: true,
                      prompt:'--',
                      start_year: 1990,
                      end_year: (Time.now.year),
                      date_separator: '%s'),
                    "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
      </div>
    </div>

    <div class="pet-form-group">
      <div class='pet-form-text-wrap'>
        <label class="pet-form-text">
        Age
        </label>
      </div>
        <%= f.text_field :age, class:"pet-age-form", id:"age", placeholder:"年齢", maxlength:"3" %>
        <p class='pet-info-text'>※生年月日の入力があれば、詳細画面で自動表示されます</p>
    </div>

    <div class='register-btn'>
      <p class='enter-btn'>
        <%= image_submit_tag("enter_btn3.png", class:"btn") %>
      </p>
    </div>
  </div>
<% end %>

<%= render "shared/footer" %>

app/views/pets/new.html.erb
<%= render "shared/second-header"%>


<%= form_with model: @pet, url: user_pets_path, class: 'registration-main', local: true do |f| %>
  <div class='pet-form-wrap'>
    <div class='pet-form-header'>
      <h1 class='pet-form-header-text'>
        YourPet
      </h1>
    </div>

    
  <%= render "shared/error_messages", model: f.object %>

    <div class="pet-form-group">
      <div class='pet-form-text-wrap'>
        <label class="pet-form-text">
        <span class='not-nil'>*</span> Name
        </label>
      </div>
      <%= f.text_field :name, class:"pet-name-form", id:"name", placeholder:"ペットの名前", maxlength:"20" %>
    </div>

    <div class="pet-form-group">
      <div class='pet-form-text-wrap'>
        <label class="pet-form-text">
        <span class='not-nil'>*</span> Image
        </label>
      </div>
      <%= f.file_field :image, class:"pet-image-form", id:"pet-image" %>
    </div>

    <div class="pet-form-group">
      <div class='pet-form-text-wrap'>
        <label class="pet-form-text">
        <span class='not-nil'>*</span> Pet Type
        </label>
      </div>
      <div class='pet-type-form'>
        <%= f.collection_select(:pet_type_id, PetType.all, :id, :name, {}, {class:"pet-type-select"}) %>
      </div>
    </div>

    <div class="pet-form-group">
      <div class='pet-form-text-wrap'>
        <label class="pet-form-text">
        <span class='not-nil'>*</span> Feature
        </label>
      </div>
      <%= f.text_area :feature, class:"pet-feature-form", id:"feature", placeholder:"種類や色など、特徴を記入" %>
    </div>

    <div class="pet-form-group">
      <div class='pet-form-text-wrap'>
        <label class="pet-form-text">
         Birthday
        </label>
      </div>
      <div class='input-pet-birth-wrap'>
        <%= raw sprintf(
                    f.date_select(
                      :birthday,
                      class:'select-pet-birth',
                      id:"pet-birth-date",
                      use_month_numbers: true,
                      prompt:'--',
                      start_year: 1990,
                      end_year: (Time.now.year),
                      date_separator: '%s'),
                    "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
      </div>
    </div>

    <div class="pet-form-group">
      <div class='pet-form-text-wrap'>
        <label class="pet-form-text">
        Age
        </label>
      </div>
        <%= f.text_field :age, class:"pet-age-form", id:"age", placeholder:"年齢", maxlength:"3" %>
        <p class='pet-info-text'>※生年月日の入力があれば、詳細画面で自動表示されます</p>
    </div>

    <div class='register-btn'>
      <p class='enter-btn'>
        <%= image_submit_tag("enter_btn3.png", class:"btn") %>
      </p>
    </div>
  </div>
<% end %>

<%= render "shared/footer" %>

app/views/pets/show.html.erb
<%= render "shared/second-header"%>


<div class='registration-main'>
  <div class='mypage-wrap'>
    <div class='mypage-header'>
      <h1 class='mypage-header-text'>
        Pet Info
      </h1>
    </div>

    

    <div class="mypage-group">
      <div class='mypage-text-wrap'>
        <label class="mypage-text">
        Name
        </label>
      </div>
      <p class='nickname-mypage'><%= @pet.name %></p>
    </div>

    <div class="mypage-group">
      <div class='mypage-text-wrap'>
        <label class="mypage-text">
        Image
        </label>
      </div>
      <div class="article-show-group">
        <%= image_tag @pet.image ,class:"article-show-image" %>
      </div>
    </div>



    <div class="mypage-group">
      <div class='mypage-text-wrap'>
        <label class="mypage-text">
        Pet Type
        </label>
      </div>
      <p class='gender-mypage'><%= @pet.pet_type.name %></p>
    </div>
    <div class="mypage-group">
      <div class='mypage-text-wrap'>
        <label class="mypage-text">
        Feature
        </label>
      </div>
      <p class='birthday-mypage'><%= @pet.feature %></p>
    </div>

    <div class="mypage-group">
      <div class='mypage-text-wrap'>
        <label class="mypage-text">
        Birthday
        </label>
      </div>
      <% unless @pet.birthday.nil? %>
        <p class='nickname-mypage', id='pet-birthday'><%= @pet.birthday %></p>
      <% else %>
        <p class='have-pet-mypage'>Prease setting</p>
      <% end %>
    </div>

    <div class="mypage-group">
      <div class='mypage-text-wrap'>
        <label class="mypage-text">
        Age
        </label>
      </div>
      <% unless @pet.age.nil? %>
        <p class='nickname-mypage', id='pet-age'><%= @pet.age %></p>
      <% else %>
        <p class='have-pet-mypage', id='pet-age'>Prease setting</p>
      <% end %>
    </div>

    <% if current_user == @pet.user %>
      <div class='go-edit-btn'>
        <%= link_to 'Edit Pet Info', edit_user_pet_path(@pet.id), class: "go-edit" %>
      </div>
    <% end %>

    <% if current_user == @pet.user %>
      <div class='go-delete-btn'>
        <%= link_to 'Delete Pet Info...?', user_pet_path(@pet.id), method: :delete, data: { confirm: "【確認】このPet infoを削除してもよろしいですか？" }, class: "go-delete" %>
      </div>
    <% end %>

  </div>
</div>

<%= render "shared/footer" %>