config/routes.rb
Rails.application.routes.draw do

  get 'users/show'
  devise_for :users, controllers: {
    registrations: "users/registrations",
  }
  root to: 'articles#index'
  get 'tasks/:id' , to: 'articles#notice'
  resources :users, only: [:show] do
    resources :pets, only: [:new, :create, :show, :edit, :update, :destroy]
    resources :tasks
  end
  resources :articles, only: [:new, :create, :show, :edit, :update, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, {presence: { message: 'は必須です' }, format: { with: VALID_EMAIL_REGEX, message: 'は正しく入力してください' }, uniqueness: { case_sensitive: false, message: 'が既に登録されています' }}

  with_options presence: { message: 'は必須です' } do
    validates :nickname
    validates :password, confirmation: true, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{6,100}+\z/i, message: 'はアルファベットと数字を含む6文字以上必要です' }, on: :create
    validates :password_confirmation, on: :create
    validates :gender_id, numericality: { message: 'を選んでください' }
    validates :birthday
  end

  validates :profile, length: { maximum: 200, message: 'は200文字以内で記入してください' }

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  has_many :articles
  has_many :pets

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender
  belongs_to :have_pet
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_update_path_for(_resource)
    user_path(@user.id)
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:nickname, :gender_id, :birthday, :image, :have_pet_id, :profile])
  end

  # def update_resource(resource, params)
  #   resource.update_without_password(params)
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]


  def show
    @user = User.find(params[:id])
  end

  private


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/show.html.erb
<%= render "shared/second-header"%>


<div class='registration-main'>
  <div class='mypage-wrap'>
    <div class='mypage-header'>
      <h1 class='mypage-header-text'>
        MyPage
      </h1>
    </div>

    

    <div class="mypage-group">
      <div class='mypage-text-wrap'>
        <label class="mypage-text">
        NickName
        </label>
      </div>
      <p class='nickname-mypage'><%= @user.nickname %></p>
    </div>

    <div class="mypage-group">
      <div class='mypage-text-wrap'>
        <label class="mypage-text">
        Email
        </label>
      </div>
      <p class='email-mypage'><%= @user.email %></p>
    </div>



    <div class="mypage-group">
      <div class='mypage-text-wrap'>
        <label class="mypage-text">
        Gender
        </label>
      </div>
      <p class='gender-mypage'><%= @user.gender.name %></p>
    </div>
    <div class="mypage-group">
      <div class='mypage-text-wrap'>
        <label class="mypage-text">
        Birthday
        </label>
      </div>
      <p class='birthday-mypage'><%= @user.birthday %></p>
    </div>

    <div class="mypage-group">
      <div class='mypage-text-wrap'>
        <label class="mypage-text">
        Have pets?
        </label>
      </div>
      <% unless @user.have_pet_id.nil? %>
        <p class='nickname-mypage'><%= @user.have_pet.name %></p>
      <% else %>
        <p class='have-pet-mypage'>Prease setting</p>
      <% end %>
    </div>

    <div class="mypage-group">
      <div class='mypage-text-wrap'>
        <label class="mypage-text">
        Profile
        </label>
      </div>
      <p class='profile-mypage'><%= current_user.profile %></p>
    </div>

    <div class="all-pets-group">
      <div class='mypage-text-wrap'>
        <label class="mypage-text">
        Your Pets
        </label>
      </div>
        <div class='pet-list-contents'>
          <ul class='all-pet-lists'>
            <% @user.pets.order('created_at DESC').each do |pet| %>
                <li class='pet-list'>
                  <%= link_to user_pet_path(pet.id), class: 'pet-info' do %>
                    <div class='pet-img-content'>
                        <%= image_tag pet.image, class: "pet-icon" %>
                    </div>
                    <div class='pet-name'>
                        <span><%= pet.name %></span>
                    </div>
                  <% end %>
                </li>
            <% end %>
          </ul>
                      <div class='add-pet'><%= link_to 'add Pet', new_user_pet_path(@user.id), class: "add-pet-btn" %></div>

        </div>

      <div class="all-pets-group">
        <div class='mypage-text-wrap'>
          <label class="mypage-text">
          Your Articles
          </label>
        </div>
        <div class='your-all-articles'>
          all your articles

          <ul class='article-lists'>

            <% @user.articles.order('created_at DESC').each do |article| %>
                <li class='list'>
                  <%= link_to article_path(article.id), class: "article-content" do %>
                    <div class='article-img-content'>
                      <%= image_tag article.image, class: "article-img" %>
                    </div>
                    <div class='article-info'>
                      <h3 class='article-name'>
                        <%= article.title %>
                      </h3>
                      <h4 class='user-nickname'>
                        <span><%= article.user.nickname %></span>
                      </h4>
                    </div>
                  <% end %>
                </li>
            <% end %>
          </ul>
        </div>
      </div>



    </div>

    <% if current_user == @user %>
      <div class='go-edit-btn'>
        <%= link_to 'Edit My Page', edit_user_registration_path, class: "go-edit" %>
      </div>
    <% end %>

  </div>
</div>

<%= render "shared/footer" %>